In [6]:
# pair stance classification
import pandas as pd
import os, sys
import importlib
import numpy as np
sys.path.append("..")
import copy


import experimenter
from experimenter import evaluation
from experimenter.utils import modeling, training, data, text, utils
importlib.reload(experimenter)
importlib.reload(text)
importlib.reload(modeling)
importlib.reload(evaluation)
importlib.reload(training)
importlib.reload(data)
importlib.reload(utils)

configs = {"epochs": 25,
           "experiment_output_path": "local/final_training.json", 
           "log_interval": 1, "model_path": "local/model.state", 
           "processor": {
                "module": "experimenter.utils.data",
                "class": "PairStanceProvider",
                "params":{"input_path": "/Users/jkhouja/workspace/repo/arabic_media/data/for training/batch_0_to_15000_pairs_eq_weight_random.csv",
                          "seq_len": {'inp':[50,50], 'label':[1],'mask':[1]}, "batch_size": 4, "splits": [.7, .2, .1], "drop_last":True,  "shuffle": True, "vocab_path": "local/vocab.json"}},
           "model":{
                "module": "experimenter.utils.modeling",
                "class": "RNNPairModel",
                "params":{"embedding_dim": 20, "hidden_dim": 100, "num_classes": 3, "dropout": 0, "max_seq_len": {"eval": 1, "value": "config['processor']['params']['seq_len']['inp'][0]"}}},
           
            "evaluator":{
                "module": "experimenter.evaluation",
                "class": "ListEvaluator",
                "params": {"loss_f": [{"module": 'torch.nn', "class": 'CrossEntropyLoss', "params": {'reduction': 'none'}}],
                          "metrics_f": [{"module": 'experimenter.evaluation', "class": 'Accuracy', "params": {}}]}},
            "optimizer":{
                "module": "torch.optim",
                "class": "Adam",
                "params":{
                    "params": {
                    "eval": 1,
                    "value": "config['model']['model'].parameters()"},
                'lr':  0.001}}
           }



lm_configs = {"epochs": 5,
           "experiment_output_path": "local/final_training.json", 
           "log_interval": 1, "model_path": "local/model.state", 
           "processor": {
                "module": "experimenter.utils.data",
                "class": "LMProvider",
                "params":{"input_path": "/Users/jkhouja/workspace/repo/arabic_media/data/pairs/batch_0_to_15000_pairs_eq_weight_random.csv",
                          "seq_len": {'inp':[50], 'label':[50],'mask':[1]}, "batch_size": 4, "splits": [.1, .2, .1, .6], "drop_last":"False",  "shuffle": "True", "vocab_path": "local/vocab.json"}},
           "model":{
                "module": "experimenter.utils.modeling",
                "class": "RNNLMModel",
                "params":{"embedding_dim": 8, "hidden_dim": 30, "dropout": 0, "max_seq_len": {"eval": 1, "value": "config['processor']['params']['seq_len']['inp'][0]"}}},
           
            "evaluator":{
                "module": "experimenter.evaluation",
                "class": "ListEvaluator",
                "params": {"loss_f": [{"module": 'torch.nn', "class": 'CrossEntropyLoss', "params": {'reduction': 'none'}}]}},
            "optimizer":{
                "module": "torch.optim",
                "class": "Adam",
                "params":{
                    "params": {
                    "eval": 1,
                    "value": "config['model']['model'].parameters()"},
                'lr':  0.001}}
           }

multi_configs = {"epochs": 2,
           "experiment_output_path": "local/final_training.json", 
           "log_interval": 1, "model_path": "local/model.state", 
           "processor": {
                "module": "experimenter.utils.data",
                "class": "MultiLMPairProvider",
                "params":{"input_path": "/Users/jkhouja/workspace/repo/arabic_media/data/for training/batch_0_to_15000_pairs_eq_weight_random.csv",
                          "seq_len": {'inp':[50, 50], 'label':[50, 1],'mask':[1, 1]}, "batch_size": 4, "splits": [.7, .2, .1], "drop_last":True,  "shuffle": True, "vocab_path": "local/vocab.json"}},
           "model":{
                "module": "experimenter.utils.modeling",
                "class": "RNNMultiLMPairModel",
                "params":{"embedding_dim": 20, "hidden_dim": 100, "dropout": 0, "lm_classes": {"eval": 1, "value":"config['processor']['params']['vocab_size']"},  "num_classes":3 , "max_seq_len": {"eval": 1, "value": "config['processor']['params']['seq_len']['inp'][0]"}}},
           
            "evaluator":{
                "module": "experimenter.evaluation",
                "class": "ListEvaluator",
                "params": {"loss_f": [{"module": 'torch.nn', "class": 'CrossEntropyLoss', "params": {'reduction': 'none'}}, {"module": 'torch.nn', "class": 'CrossEntropyLoss', "params": {'reduction': 'none'}}],
                          "metrics_f": [{"module": 'experimenter.evaluation', "class": 'Dummy', "params": {}}, {"module": 'experimenter.evaluation', "class": 'Accuracy', "params": {}}]}},
            "optimizer":{
                "module": "torch.optim",
                "class": "Adam",
                "params":{
                    "params": {
                    "eval": 1,
                    "value": "config['model']['model'].parameters()"},
                'lr':  0.001}}
           }

#unlabeled_data = [{'inp':["يالت رجل", "قال رجلي"],'label':[['agree']],'mask':[1]}]*10

config =copy.deepcopy(multi_configs)

# Initialize two models
trainer_smart = training.BasicTrainer(config)

res_smart = trainer_smart.train_model()


All loaded data size:8754
Will create train, dev, test(s) splits
Total params: 58807
Starting training:


KeyboardInterrupt: 

In [67]:
import os, sys
import importlib
import numpy as np
sys.path.append("..")

import experimenter
from experimenter.MultiTask.loader import MovieCorpus

importlib.reload(experimenter.MultiTask.loader)
from experimenter.MultiTask.loader import MovieCorpus

mv = MovieCorpus(root_path="/Users/jkhouja/workspace/experiments/", input_paths=["moviecorpus"], label_col="response")

s = mv()


Processing corpus...

Loading conversations...


In [68]:
s[0]

['Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.',
 {'response': "Well, I thought we'd start with pronunciation, if that's okay with you."}]

In [70]:
!python ../run_hydra.py --yaml_file="test/conf/movie.yaml"

Traceback (most recent call last):
  File "../run_hydra.py", line 21, in <module>
    raise ValueError("yaml_file attribute is missing.  Please add yaml_file=path_to_yaml")
ValueError: yaml_file attribute is missing.  Please add yaml_file=path_to_yaml


In [79]:
import pandas as pd
s = pd.read_csv("preds.csv")
s.head(200)

inp  \
0  ['Sure. How much does the job pay? Sure, if th...   
1                                   ['Oh, Amber...']   
2                 ['<UNK> What makes you say that?']   
3  ['Look, Eddie, Im tellin you - I didnt touch h...   
4  ['Nothing, Wade, Ive been thinking. You dont g...   
5                ['Now, dont get into any trouble.']   
6  ['Im sorry I... yelled at you. Was it <UNK> I ...   
7                                ['Im in <UNK> Lt.']   

                                               label mask  \
0  ['You wouldnt consider going over Niagara Fall...  [1]   
1  ['I -- I -- I -- I -- I <UNK> <UNK> just wante...  [1]   
2           ['Your life flashing before your <UNK>']  [1]   
3  ['Well, you shoulda because nobodys gonna beli...  [1]   
4         ['I saw Mel Gordon in here this morning.']  [1]   
5                                     ['Take care.']  [1]   
6                                    ['Thats okay.']  [1]   
7                         ['<UNK> us up to a <UNK>']  [1]   

                                                 out  \
0  [[[-20.401412963867188, -22.40707015991211, -2...   
1  [[[-20.877586364746094, -20.595043182373047, -...   
2  [[[-23.588829040527344, -20.16618537902832, -2...   
3  [[[-19.281301498413086, -23.21527862548828, -1...   
4  [[[-21.070552825927734, -18.70219612121582, -1...   
5  [[[-20.708263397216797, -19.05992889404297, -9...   
6  [[[-22.6044979095459, -21.06704330444336, -9.9...   
7  [[[-22.565155029296875, -21.987918853759766, -...   

                                                pred  \
0  ['I dont have it. to Niagara Falls without a <...   
1  ['<UNK> <UNK> I dont you dont you dont you don...   
2  ['I <UNK> flashing <UNK> the <UNK> <UNK> <UNK>...   
3  ['I I dont <UNK> nobodys dont have you <UNK> w...   
4  ['I dont it. Gordon <UNK> <UNK> and morning. <...   
5  ['You it <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <...   
6  ['I what <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <...   
7  ['<UNK> <UNK> is a the <UNK> <UNK> <UNK> <UNK>...   

                                                meta  
0  [[[-0.9813107252120972, 0.9775485992431641, -0...  
1  [[[0.317582368850708, -0.589380145072937, -0.1...  
2  [[[-0.8720320463180542, 0.0005405789124779403,...  
3  [[[-0.8098210692405701, 0.23616184294223785, -...  
4  [[[-0.798618495464325, 0.7513481378555298, -0....  
5  [[[0.25530070066452026, -0.5741497278213501, -...  
6  [[[-0.9876314401626587, 0.2795756459236145, -0...  
7  [[[-0.9498781561851501, -0.020232347771525383,...

In [261]:
# Evaluate on training
selected_data = trainer_smart.processor.get_data()

trainer_smart._evaluate_batches(selected_data[0])

[0.8669170476812541]

In [252]:
trainer_smart.evaluator.reset()
correct = 0
total = 0
res = []
for j, b in enumerate(selected_data[2]):
    #print(j)
    decoded_batch = trainer_smart.processor.decode(trainer_smart.processor._from_batch(b), list_input=True)
    #print(decoded_batch)
    res.append(trainer_smart.model(b))
    val_loss = trainer_smart.evaluator.update_batch(res[j])
    print(val_loss)
    print(trainer_smart.evaluator.get_metrics(res[j]))
    pred = trainer_smart.predict(decoded_batch, decode=False)
    current_corrects = sum([p['pred'][0] == p['label'][0] for p in pred])
    current_total = len(pred)
    print(current_corrects / current_total)
    #[print("||".join([str(p['pred'][0][0]), str(p['label'][0][0])])) for p in pred]
    print("===================")
    correct += current_corrects
    total += current_total
print(j, val_loss)
correct / total

[1.0]
[array(1., dtype=float32)]
1.0
[0.75]
[array(0.5, dtype=float32)]
0.5
[0.75]
[array(0.75, dtype=float32)]
0.75
[0.75]
[array(0.75, dtype=float32)]
0.75
[0.8]
[array(1., dtype=float32)]
1.0
[0.7916666666666666]
[array(0.75, dtype=float32)]
0.75
[0.7857142857142857]
[array(0.75, dtype=float32)]
0.75
[0.75]
[array(0.5, dtype=float32)]
0.5
[0.6944444444444444]
[array(0.25, dtype=float32)]
0.25
[0.725]
[array(1., dtype=float32)]
0.75
[0.7045454545454546]
[array(0.5, dtype=float32)]
0.75
[0.6875]
[array(0.5, dtype=float32)]
0.5
[0.6730769230769231]
[array(0.5, dtype=float32)]
0.5
[0.6785714285714286]
[array(0.75, dtype=float32)]
0.75
[0.7]
[array(1., dtype=float32)]
1.0
[0.6875]
[array(0.5, dtype=float32)]
0.5
[0.6764705882352942]
[array(0.5, dtype=float32)]
0.5
[0.6666666666666666]
[array(0.5, dtype=float32)]
0.75
[0.6578947368421053]
[array(0.5, dtype=float32)]
0.5
[0.675]
[array(1., dtype=float32)]
1.0
[0.6785714285714286]
[array(0.75, dtype=float32)]
0.25
[0.6704545454545454]
[arra

0.75
[0.6565040650406504]
[array(0.5, dtype=float32)]
0.5
[0.655241935483871]
[array(0.5, dtype=float32)]
0.0
[0.656]
[array(0.75, dtype=float32)]
0.75
[0.6587301587301587]
[array(1., dtype=float32)]
1.0
[0.6594488188976378]
[array(0.75, dtype=float32)]
0.75
[0.66015625]
[array(0.75, dtype=float32)]
0.75
[0.6608527131782945]
[array(0.75, dtype=float32)]
0.75
[0.6596153846153846]
[array(0.5, dtype=float32)]
0.5
[0.6603053435114504]
[array(0.75, dtype=float32)]
0.75
[0.6609848484848485]
[array(0.75, dtype=float32)]
0.75
[0.6616541353383458]
[array(0.75, dtype=float32)]
0.75
[0.664179104477612]
[array(1., dtype=float32)]
1.0
[0.6611111111111111]
[array(0.25, dtype=float32)]
0.5
[0.65625]
[array(0., dtype=float32)]
0.0
[0.656934306569343]
[array(0.75, dtype=float32)]
0.75
[0.6557971014492754]
[array(0.5, dtype=float32)]
0.75
[0.6528776978417267]
[array(0.25, dtype=float32)]
0.25
[0.6535714285714286]
[array(0.75, dtype=float32)]
0.75
[0.6524822695035462]
[array(0.5, dtype=float32)]
0.5
[0.6

0.6376146788990825

In [40]:
unlabeled_data = trainer_smart.processor.get_data()
#pred = trainer_smart._evaluate_batches(unlabeled_data[0])
pred = [p['pred'][1] == p['label'][1] for p in pred]
pred

[0.0, 0.3403890160183066]

In [121]:
correct = 0
total = 0
for b in selected_data[0]:
    decoded_batch = trainer_smart.processor.decode(trainer_smart.processor._from_batch(b), list_input=True)
    pred = trainer_smart.predict(decoded_batch, decode=False)
    correct += sum([p['pred'][0] == p['label'][0] for p in pred])
    total += len(pred)

#sum(pred) / len(pred) 
correct / total

0.42660550458715596

In [189]:
trainer_smart.evaluator.metrics_f[0](res[j]['pred'][0], res[j]['label'][0])
print(res[j]['pred'][0])
print(res[j]['label'][0])
[print("|".join([str(p['pred'][0][0]), str(p['label'][0][0])])) for p in pred]

tensor([[1],
        [2],
        [2],
        [1]])
tensor([[1],
        [0],
        [1],
        [1]])
2|1
1|1
2|0
0|1


[None, None, None, None]

In [196]:
res[j]['inp'][0]

tensor([[34, 13,  4, 15, 14,  6, 22, 11, 29,  2, 30,  3, 22,  6,  4,  2,  8, 15,
         22,  4,  3, 15,  9,  6,  2,  2, 24,  2,  4,  3,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0],
        [ 4, 34,  9, 28,  4, 28,  4,  9,  6,  4,  2,  7, 12,  4, 31, 30,  6, 21,
          8, 11, 41,  6, 34,  5, 12,  6, 15, 24, 11,  8,  6,  3, 34,  4, 27, 26,
          4,  9,  6,  4],
        [ 3, 11,  8, 15, 32,  6,  9, 36, 27, 16,  6,  4,  2,  9, 10, 22, 15, 27,
          4,  9,  6, 29,  4,  2, 28,  3,  2, 14,  6, 27, 15,  6,  9, 12, 13, 15,
          4, 35, 35,  6],
        [ 4,  2,  8, 11,  2,  4, 12,  6, 15, 31, 27, 32, 35, 35,  6, 11, 15,  7,
         32, 32,  6,  3, 13,  4, 24, 29, 21,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0]])

In [197]:
pred[0]['inp'][0]

[3,
 11,
 8,
 15,
 32,
 6,
 9,
 36,
 27,
 16,
 6,
 4,
 2,
 9,
 10,
 22,
 15,
 27,
 4,
 9,
 6,
 29,
 4,
 2,
 28,
 3,
 2,
 14,
 6,
 27,
 15,
 6,
 9,
 12,
 13,
 15,
 4,
 35,
 35,
 0]

In [202]:
type(res[j]['inp'][0])

torch.Tensor

In [51]:
unlabeled_data = trainer_smart.processor.upload_data()
pred = trainer_smart.predict(unlabeled_data[:1000], decode=False)
pred = [p['pred'][0] == p['label'][0] for p in pred]
sum(pred) / len(pred) 

0.56

In [300]:
# Predict on unlabled data
def get_ent(preds):
    res = []
    for example in preds:
        ent = 0
        for p in example:
            ent += -p * np.log2(p)
        res.append(ent)
        
    return res

import random
top_n = 200
num_steps = range(10)
for step in num_steps:
    print("step {}".format(step))
    pred = trainer_smart.predict(unlabeled_data, decode=True)

    outs = [o for p in pred for o in p['meta']]
    ent = get_ent(outs)
    ent = np.array(ent)
    print(ent.mean())
    idx = (-ent).argsort()[:top_n]
    #print("selected examples based on entropy: ")
    #print(idx)
    filtered = [unlabeled_data[s] for s in idx]
    random_d = [unlabeled_data[s] for s in random.sample(range(len(unlabeled_data)), top_n)]

    # Update remaining
    print("Remaining data before / after filtering the learned batch")
    print(len(unlabeled_data))
    unlabeled_data = [s for i, s in enumerate(unlabeled_data) if i not in idx]
    print(len(unlabeled_data))

    #print(random)
    #print(filtered)

    #Retrain
    filtered_encoded = trainer_smart.processor(filtered, data_type='full', list_input= True, as_batches=True)
    random_encoded = trainer_smart.processor(random_d, data_type='full', list_input= True, as_batches=True)
    res_smart = trainer_smart.train_model([filtered_encoded, val_data, test_data])
    res_random = trainer_random.train_model([random_encoded, val_data, test_data])


step 0
1.4463678059057392
Remaining data before / after filtering the learned batch
5052
4852
Starting training:
Epoch: 11: Train loss (last batch): 1.0623605251312256, validation loss: 1.0581321716308594
Best model saved at: model.state
Epoch: 12: Train loss (last batch): 0.7871716618537903, validation loss: 1.0428305864334106
Best model saved at: model.state
Epoch: 13: Train loss (last batch): 1.1186940670013428, validation loss: 1.0667556524276733
Epoch: 14: Train loss (last batch): 1.3207297325134277, validation loss: 1.088484525680542
Epoch: 15: Train loss (last batch): 1.049099326133728, validation loss: 1.0591458082199097
Test loss: 1.0410854816436768
Starting training:
Epoch: 11: Train loss (last batch): 0.9175735712051392, validation loss: 1.0657908916473389
Best model saved at: model.state
Epoch: 12: Train loss (last batch): 1.0900952816009521, validation loss: 1.0391796827316284
Best model saved at: model.state
Epoch: 13: Train loss (last batch): 0.9136359691619873, validati

Best model saved at: model.state
Test loss: 0.9901295900344849
Starting training:
Epoch: 41: Train loss (last batch): 1.2643591165542603, validation loss: 1.0451629161834717
Best model saved at: model.state
Epoch: 42: Train loss (last batch): 1.170201063156128, validation loss: 1.052954912185669
Epoch: 43: Train loss (last batch): 0.956839919090271, validation loss: 1.0390136241912842
Best model saved at: model.state
Epoch: 44: Train loss (last batch): 1.3444180488586426, validation loss: 1.0519754886627197
Epoch: 45: Train loss (last batch): 0.9354345798492432, validation loss: 1.061521053314209
Test loss: 1.0727882385253906
step 7
1.3193084428125657
Remaining data before / after filtering the learned batch
3652
3452
Starting training:
Epoch: 46: Train loss (last batch): 0.9979891777038574, validation loss: 1.013409972190857
Best model saved at: model.state
Epoch: 47: Train loss (last batch): 1.0384202003479004, validation loss: 1.0270806550979614
Epoch: 48: Train loss (last batch): 0

In [330]:
ent.argmax()
ent[idx[100]]
ent[ent.argmax()]
unlabeled_data[idx[100]]['label'][0][0]
trainer_random.predict([unlabeled_data[idx[100]], unlabeled_data[idx[100]]])[0]['pred'][0][0]

'other'

In [320]:
res_smart['results']

{'during_training': {'1': {'train_loss': 1.0959333181381226,
   'val_loss': 1.0971243381500244},
  '2': {'train_loss': 1.1127394437789917, 'val_loss': 1.0927706956863403},
  '3': {'train_loss': 1.2162951231002808, 'val_loss': 1.0798826217651367},
  '4': {'train_loss': 1.1723943948745728, 'val_loss': 1.0638456344604492},
  '5': {'train_loss': 1.0028953552246094, 'val_loss': 1.0499619245529175},
  '6': {'train_loss': 1.090139627456665, 'val_loss': 1.0430418252944946},
  '7': {'train_loss': 0.9486572742462158, 'val_loss': 1.050020694732666},
  '8': {'train_loss': 1.1977633237838745, 'val_loss': 1.0444697141647339},
  '9': {'train_loss': 1.0246580839157104, 'val_loss': 1.0404095649719238},
  '10': {'train_loss': 0.6556094288825989, 'val_loss': 1.0469732284545898},
  '11': {'train_loss': 1.0623605251312256, 'val_loss': 1.0581321716308594},
  '12': {'train_loss': 0.7871716618537903, 'val_loss': 1.0428305864334106},
  '13': {'train_loss': 1.1186940670013428, 'val_loss': 1.0667556524276733},
 

In [171]:
res_random['results']

{'during_training': {'1': {'train_loss': 0.9932723045349121,
   'val_loss': 1.1460973024368286},
  '2': {'train_loss': 1.8655883073806763, 'val_loss': 0.9856749773025513},
  '3': {'train_loss': 0.5568922758102417, 'val_loss': 0.9643186330795288},
  '4': {'train_loss': 0.8071258664131165, 'val_loss': 0.9565287828445435},
  '5': {'train_loss': 0.5423922538757324, 'val_loss': 0.9556002020835876},
  '6': {'train_loss': 0.9349740743637085, 'val_loss': 0.9569883942604065},
  '7': {'train_loss': 1.3021361827850342, 'val_loss': 0.9552294015884399},
  '8': {'train_loss': 0.726514458656311, 'val_loss': 0.9544289708137512},
  '9': {'train_loss': 1.0989142656326294, 'val_loss': 0.955574095249176},
  '10': {'train_loss': 0.4896788001060486, 'val_loss': 0.955385684967041},
  '11': {'train_loss': 1.331813097000122, 'val_loss': 0.955652117729187},
  '12': {'train_loss': 1.322219729423523, 'val_loss': 0.956355631351471},
  '13': {'train_loss': 0.5277446508407593, 'val_loss': 0.9499547481536865},
  '14'

In [153]:
import yaml
f = yaml.load(open("results.json", 'r'))
with open("results.yaml", 'w') as out:
    out.write(yaml.dump(f))

/Users/jkhouja/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  


In [157]:
import json
json.dump({'a':1}, open('tst.json', 'w'))

In [147]:
torch.exp(torch.tensor(5.44))

tensor(230.4422)

In [62]:
# Testing PP:
import sys
import torch
sys.path.append("..")
from experimenter.evaluation import ListEvaluator
import torch.nn
from torch.nn import CrossEntropyLoss

In [126]:
# Same word along the sequence
ignore_idx = 0
b_size = 2
seq_len = 20
vocab_size = 3000
act_len = 3
correct_id = 1

config = {'device':'cpu', 'evaluator': {'params' :{
    "loss_f": [
    {"module": 'torch.nn', "class": 'CrossEntropyLoss', "params": {'reduction': 'none', 'ignore_index': ignore_idx}} 
    ],
    "metrics_f": [
        {"module": 'experimenter.evaluation', "class": 'Accuracy', "params": {}}
    ]
}}}

evaluator = ListEvaluator(config)

# Create perfect matching data
# Label [outputs(1), b_size, seq_len]
label = torch.tensor([[[correct_id] * act_len + [ignore_idx] * (seq_len - act_len),[correct_id] * act_len + [ignore_idx] * (seq_len - act_len)]], dtype=torch.long) # sequence where the correct labels are 1,1,1

# Output [outputs(1), b_size, vocab_size, seq_len]
out_perfect = torch.zeros((1,b_size,vocab_size,seq_len), dtype=torch.float)  # Prediction probabilities
out_perfect[0,:,correct_id,:] = 100

# Mask [outputs(1), ]
mask = torch.tensor([[1]])

record = {'out': out_perfect, 'label':label, 'mask':mask}

evaluator.reset()
res = evaluator.update_batch_loss(record)
print(res)
assert res == [0]

[0.0]


In [142]:
# Perfect prediction along the sequence
ignore_idx = 0
b_size = 2
seq_len = 20
vocab_size = 3000


config = {'device':'cpu', 'evaluator': {'params' :{
    "loss_f": [
    {"module": 'torch.nn', "class": 'CrossEntropyLoss', "params": {'reduction': 'none', 'ignore_index': ignore_idx}} 
    ],
    "metrics_f": [
        {"module": 'experimenter.evaluation', "class": 'Accuracy', "params": {}}
    ]
}}}

evaluator = ListEvaluator(config)

# Create perfect matching data
# Label [outputs(1), b_size, seq_len]
label = torch.tensor([[[1,2,3,ignore_idx, ignore_idx],[1,2,3,ignore_idx, ignore_idx]]], dtype=torch.long) # sequence where the correct labels are 1,1,1

# Output [outputs(1), b_size, vocab_size, seq_len]
out_perfect = torch.zeros((1,b_size,vocab_size,label.shape[2]), dtype=torch.float)  # Prediction probabilities
out_perfect[0,:,1,0] = 40
out_perfect[0,:,2,1] = 40
out_perfect[0,:,3,2] = 40
print(out_perfect)

# Mask [outputs(1), ]
mask = torch.tensor([[1]])

record = {'out': out_perfect, 'label':label, 'mask':mask}

evaluator.reset()
res = evaluator.update_batch_loss(record)
print(res)
assert res == [0]

tensor([[[[ 0.,  0.,  0.,  0.,  0.],
          [40.,  0.,  0.,  0.,  0.],
          [ 0., 40.,  0.,  0.,  0.],
          ...,
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  0.,  0.],
          [40.,  0.,  0.,  0.,  0.],
          [ 0., 40.,  0.,  0.,  0.],
          ...,
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]])
[0.0]


In [133]:
label.shape

torch.Size([1, 2, 5])

In [74]:
label = torch.tensor([[1,1,1]], dtype=torch.long) # sequence where the correct labels are 1,1,1

out_perfect = torch.zeros((1,2,3), dtype=torch.float)  # Prediction probabilities
out_perfect[:,1,:] = 10

ce(out_perfect, label)

tensor([[4.5399e-05, 4.5399e-05, 4.5399e-05]])

In [45]:
b_size = 2
seq_len = 3
vocab_size = 10

out = torch.zeros((b_size,vocab_size,seq_len))
out[:,1,:] = 1
out

tensor([[[0., 0., 0.],
         [1., 1., 1.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [1., 1., 1.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])